### PR TITLE
feat: expose bucket_endpoint variable

### PR DESCRIPTION
**Pull request by kierramarie**
### Description

Optional variable cos_bucket_endpoint was added to expose scc_instance_settings bucket endpoint.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Can you update the complete example so it passes a value for `cos_bucket_endpoint` ? I suggest to maybe go with the `direct` endpoint value

**Comment by kierramarie** [comment]
@ocofaigh I got this error when trying to run the complete example with changes - `Can't configure a value for "object_storage.0.bucket_endpoint": its value will be decided automatically based on the result of applying this configuration.`

**Comment by ocofaigh** [comment]
@kierramarie Interesting - can you try a test with hard coding the value of an existing bucket and endpoint (that you didnt create using the same terraform apply as the module). Then at least we will know if the feature works at all with the provider

**Comment by kierramarie** [comment]
@ocofaigh okay, yeah. I used a bucket I created in the GUI and I still got the same error. And this is the name of the error; `Error: Value for unconfigurable attribute`

**Comment by ocofaigh** [comment]
@kierramarie please create a provider issue

**Comment by ocofaigh** [comment]
@kierramarie Actually, seems I already created a provider issue - the problem is the docs -> https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5110

**Pull request closed without merging**
